/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Pretendard', 'sans-serif'],
      },
      backgroundColor: {
        primary: '#FBFBFB',
        secondary: '#F1F1F1',
        dark: '#1C1C1C',
        darker: '#2E2E2E',
        accent: '#019B98',
        accentLight: '#55CCC9',
        accentLighter: '#C1FFFF',
        danger: '#DD0025',
        muted: '#C8C8C8',
        deepBlue: '#014E60',
        softBlue: '#3F7A8D',
      },
      textColor: {
        primary: '#FBFBFB',
        secondary: '#F1F1F1',
        dark: '#1C1C1C',
        darker: '#2E2E2E',
        accent: '#019B98',
        accentLight: '#55CCC9',
        accentLighter: '#C1FFFF',
        danger: '#DD0025',
        muted: '#C8C8C8',
        deepBlue: '#014E60',
        softBlue: '#3F7A8D',
      },
      colors: {
        primary: '#FBFBFB',
        secondary: '#F1F1F1',
        dark: '#1C1C1C',
        darker: '#2E2E2E',
        accent: '#019B98',
        accentLight: '#55CCC9',
        accentLighter: '#C1FFFF',
        danger: '#DD0025',
        muted: '#C8C8C8',
        deepBlue: '#014E60',
        softBlue: '#3F7A8D',
      },
    },
  },
  plugins: [],
};
